name: coursetracker-app

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper_ct
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOO_CLIENT_PORT: 2181
      ZOO_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka_ct
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper