spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/ct
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  mail:
    host: smtp.mail.ru
    port: 465
    username:
    password:
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  application:
    name: coursetracker

jwt:
  secret: I6IkpvaG4gRG9lIiwI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0aiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0a
  lifetime: 450000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO