spring:
  application:
    name: course-microservice
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/ctcourses
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
jwt:
  secret: I6IkpvaG4gRG9lIiwI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0aiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0a

topics:
  user: USER_DATA
  groupId: USERS_GROUP

auth-service:
  url: http://localhost:8081

server:
  port: 8082